"""Removed e-mail column in uzivatel table

Revision ID: 2e3ba8b40eeb
Revises: 6b60e92cc7a0
Create Date: 2018-12-03 14:56:49.739348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e3ba8b40eeb'
down_revision = '6b60e92cc7a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uzivatel', 'email')
    op.execute("DELETE FROM %s;" % 'uzivatel')
    op.execute(
        "INSERT INTO `uzivatel` VALUES (32,'user2','pbkdf2:sha256:50000$JX8ce48p$3fa6d725bb905fcf4e964fd6920c795ca52d3b823ddfe73fe88dd8bff3920013',6,'2018-12-13 12:07:26','2018-12-03 16:56:59','user',2),(38,'c','pbkdf2:sha256:50000$aKY7B0Ma$eb9cbfa751b083512b5ddea1b480b5f6c938ef079f0323a8ab8b9594bef20c4b',36,'2018-12-15 16:04:28','2018-12-13 13:59:01','user',49),(41,'adam','pbkdf2:sha256:50000$bRcsrhBw$edb0a2662aad0c379425d13a1cb83a72986186515d0844adebddb763014e24c7',70,'2018-12-15 16:04:39','2018-12-13 14:04:12','admin',44),(53,'xuser','pbkdf2:sha256:50000$Zu7ZtJpN$e4fe4e26ceec6cfba99fae64973e5733d6a6be6344ff50b3acd847b8bd980f89',NULL,NULL,'2018-12-15 12:49:03','user',50);")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uzivatel', sa.Column('email', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###
