"""Added activities, car deadlines table and 'seen' column

Revision ID: 7b7287ea3b0d
Revises: ee542665fc4c
Create Date: 2018-12-15 17:01:21.335577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b7287ea3b0d'
down_revision = 'ee542665fc4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deadlines_car_types',
    sa.Column('id_type', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id_type')
    )
    op.create_table('activity',
    sa.Column('id_activity', sa.Integer(), nullable=False),
    sa.Column('id_zam', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('payoff', sa.Integer(), nullable=True),
    sa.Column('id_voz', sa.Integer(), nullable=False),
    sa.Column('from_place', sa.String(length=30), nullable=False),
    sa.Column('via_place', sa.String(length=30), nullable=False),
    sa.Column('to_place', sa.String(length=30), nullable=False),
    sa.Column('begin', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('seen', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_voz'], ['vozidlo.id_voz'], ),
    sa.ForeignKeyConstraint(['id_zam'], ['zamestnanec.id_zam'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_activity')
    )
    op.create_table('deadlines_car',
    sa.Column('id_deadline', sa.Integer(), nullable=False),
    sa.Column('id_type', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('date_expiry', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['vozidlo.id_voz'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_type'], ['deadlines_car_types.id_type'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_deadline')
    )
    op.add_column('dovolena_zam_hist', sa.Column('seen', sa.Boolean(), nullable=True))
    op.add_column('dovolena_zam_hist', sa.Column('seen_by_zam', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dovolena_zam_hist', 'seen_by_zam')
    op.drop_column('dovolena_zam_hist', 'seen')
    op.drop_table('deadlines_car')
    op.drop_table('activity')
    op.drop_table('deadlines_car_types')
    # ### end Alembic commands ###
