"""Dovolena senn by zam

Revision ID: 94a02cbd9b86
Revises: b9104010b467
Create Date: 2018-12-15 09:53:24.454968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94a02cbd9b86'
down_revision = 'b9104010b467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dovolena_zam_hist', sa.Column('seen_by_zam', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dovolena_zam_hist', 'seen_by_zam')
    # ### end Alembic commands ###
