"""adde activities table

Revision ID: b9104010b467
Revises: ee542665fc4c
Create Date: 2018-12-13 19:38:11.124257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9104010b467'
down_revision = 'ee542665fc4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id_activity', sa.Integer(), nullable=False),
    sa.Column('id_zam', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('payoff', sa.Integer(), nullable=True),
    sa.Column('id_voz', sa.Integer(), nullable=False),
    sa.Column('from_place', sa.String(length=30), nullable=False),
    sa.Column('via_place', sa.String(length=30), nullable=False),
    sa.Column('to_place', sa.String(length=30), nullable=False),
    sa.Column('begin', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('seen', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_activity')
    )

    op.add_column('dovolena_zam_hist', sa.Column('seen', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dovolena_zam_hist', 'seen')
    op.drop_table('activity')
    # ### end Alembic commands ###
