"""activity added seen_by_zam

Revision ID: f2ad5820f5aa
Revises: 7b7287ea3b0d
Create Date: 2018-12-16 01:51:51.361004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2ad5820f5aa'
down_revision = '7b7287ea3b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dokument')
    op.add_column('activity', sa.Column('seen_by_zam', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'seen_by_zam')
    op.create_table('dokument',
    sa.Column('id_dokumentu', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_zam', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id_voz', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('typ_dokumentu', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('adresa_uloziste', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('platnost_do', sa.DATE(), nullable=True),
    sa.Column('zalozen_cas', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('posl_editace', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_voz'], ['vozidlo.id_voz'], name='fk_vozidlo_dokument'),
    sa.ForeignKeyConstraint(['id_zam'], ['zamestnanec.id_zam'], name='dokument_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['typ_dokumentu'], ['typ_dokumentu.id_typu'], name='dokument_ibfk_3', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_dokumentu'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
