"""activity added seen_by_zam

Revision ID: f2ad5820f5aa
Revises: 7b7287ea3b0d
Create Date: 2018-12-16 01:51:51.361004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2ad5820f5aa'
down_revision = '7b7287ea3b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('seen_by_zam', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'seen_by_zam')
    # ### end Alembic commands ###
