"""Added id_zam foreign key to Uzivatel

Revision ID: 6b60e92cc7a0
Revises: 94351efaa16e
Create Date: 2018-12-03 09:51:33.964961

"""
from alembic import op
import sqlalchemy as sa
from webapp.core import models

# revision identifiers, used by Alembic.
revision = '6b60e92cc7a0'
down_revision = '94351efaa16e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM %s;" % 'uzivatel')
    op.add_column('uzivatel', sa.Column('id_zam', sa.Integer(), nullable=False))
    op.create_foreign_key('uzivatel_zamestnanec', 'uzivatel', 'zamestnanec', ['id_zam'], ['id_zam'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uzivatel_zamestnanec', 'uzivatel', type_='foreignkey')
    op.drop_column('uzivatel', 'id_zam')
    # ### end Alembic commands ###
