"""Added Dovolena_zam_hist table for entries from Dovolena_zam

Revision ID: 94351efaa16e
Revises: fe68d98489ec
Create Date: 2018-12-02 13:29:08.551719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94351efaa16e'
down_revision = 'fe68d98489ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dovolena_zam_hist',
    sa.Column('id_zaznamu', sa.Integer(), nullable=False),
    sa.Column('id_zam', sa.Integer(), nullable=False),
    sa.Column('rok', sa.Integer(), nullable=True),
    sa.Column('od', sa.Date(), nullable=True),
    sa.Column('do', sa.Date(), nullable=True),
    sa.Column('celkem', sa.Integer(), nullable=True),
    sa.Column('potvrzeni', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_zam'], ['zamestnanec.id_zam'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_zaznamu')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dovolena_zam_hist')
    # ### end Alembic commands ###
