"""Database creation

Revision ID: cfb421ffa772
Revises: 
Create Date: 2018-10-27 10:15:24.876360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb421ffa772'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sazba',
    sa.Column('id_sazby', sa.Integer(), nullable=False),
    sa.Column('popis_sazby', sa.String(length=30), nullable=True),
    sa.Column('vyse_sazby', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_sazby')
    )
    op.create_table('typ_dokumentu',
    sa.Column('id_typu', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_typu')
    )
    op.create_table('uzivatel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('poc_prihl', sa.Integer(), nullable=True),
    sa.Column('posl_prihl', sa.TIMESTAMP(), nullable=True),
    sa.Column('cas_posl_zmeny', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vozidlo',
    sa.Column('spz', sa.String(length=10), nullable=False),
    sa.Column('znacka', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=20), nullable=True),
    sa.Column('rok_vyroby', sa.Integer(), nullable=True),
    sa.Column('vykon', sa.Integer(), nullable=True),
    sa.Column('nosnost', sa.Integer(), nullable=True),
    sa.Column('pocet_naprav', sa.Integer(), nullable=True),
    sa.Column('emisni_trida', sa.String(length=10), nullable=True),
    sa.Column('zalozeno_cas', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('posl_aktual_cas', sa.TIMESTAMP(), server_default=sa.text('now()'), server_onupdate=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('spz')
    )
    op.create_table('zamestnanec',
    sa.Column('id_zam', sa.Integer(), nullable=False),
    sa.Column('kr_jmeno', sa.String(length=20), nullable=True),
    sa.Column('prijmeni', sa.String(length=20), nullable=True),
    sa.Column('dat_nar', sa.Date(), nullable=True),
    sa.Column('trv_bydliste', sa.String(length=50), nullable=True),
    sa.Column('prech_bydliste', sa.String(length=50), nullable=True),
    sa.Column('telefon', sa.String(length=15), nullable=True),
    sa.Column('prac_sml', sa.String(length=15), nullable=True),
    sa.Column('akt_skol_id', sa.Integer(), nullable=True),
    sa.Column('akt_prohlidka', sa.Integer(), nullable=True),
    sa.Column('aktivni', sa.Integer(), nullable=True),
    sa.Column('zalozen_cas', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('posl_aktual_cas', sa.TIMESTAMP(), server_default=sa.text('now()'), server_onupdate=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_zam')
    )
    op.create_table('cinnost',
    sa.Column('id_cinnosti', sa.Integer(), nullable=False),
    sa.Column('typ_cinnosti', sa.String(length=30), nullable=False),
    sa.Column('odmena', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['odmena'], ['sazba.id_sazby'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_cinnosti')
    )
    op.create_table('dokument',
    sa.Column('id_dokumentu', sa.Integer(), nullable=False),
    sa.Column('id_zam', sa.Integer(), nullable=True),
    sa.Column('id_voz', sa.String(length=10), nullable=True),
    sa.Column('typ_dokumentu', sa.Integer(), nullable=True),
    sa.Column('adresa_uloziste', sa.String(length=30), nullable=False),
    sa.Column('platnost_do', sa.Date(), nullable=True),
    sa.Column('zalozen_cas', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('posl_editace', sa.TIMESTAMP(), server_default=sa.text('now()'), server_onupdate=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_voz'], ['vozidlo.spz'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_zam'], ['zamestnanec.id_zam'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['typ_dokumentu'], ['typ_dokumentu.id_typu'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_dokumentu')
    )
    op.create_table('dovolena_zam',
    sa.Column('id_naroku', sa.Integer(), nullable=False),
    sa.Column('id_zam', sa.Integer(), nullable=False),
    sa.Column('rok', sa.Integer(), nullable=True),
    sa.Column('narok', sa.Integer(), nullable=True),
    sa.Column('vycerpano', sa.Integer(), nullable=True),
    sa.Column('posl_aktual', sa.TIMESTAMP(), server_default=sa.text('now()'), server_onupdate=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_zam'], ['zamestnanec.id_zam'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_naroku')
    )
    op.create_table('lekarska_prohl',
    sa.Column('id_prohl', sa.Integer(), nullable=False),
    sa.Column('id_zam', sa.Integer(), nullable=False),
    sa.Column('absolvovano_dne', sa.Date(), nullable=True),
    sa.Column('platnost_do', sa.Date(), nullable=True),
    sa.Column('posl_aktual', sa.TIMESTAMP(), server_default=sa.text('now()'), server_onupdate=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_zam'], ['zamestnanec.id_zam'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_prohl')
    )
    op.create_table('pracovni_sml',
    sa.Column('id_sml', sa.Integer(), nullable=False),
    sa.Column('id_zam', sa.Integer(), nullable=False),
    sa.Column('typ_sml', sa.String(length=15), nullable=True),
    sa.Column('role_zam', sa.String(length=15), nullable=True),
    sa.Column('sjednana_dne', sa.Date(), nullable=True),
    sa.Column('platnost_do', sa.Date(), nullable=True),
    sa.Column('posl_aktual', sa.TIMESTAMP(), server_default=sa.text('now()'), server_onupdate=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_zam'], ['zamestnanec.id_zam'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_sml')
    )
    op.create_table('skoleni_ridicu',
    sa.Column('id_skol', sa.Integer(), nullable=False),
    sa.Column('id_zam', sa.Integer(), nullable=False),
    sa.Column('absolvovano_dne', sa.Date(), nullable=True),
    sa.Column('platnost_do', sa.Date(), nullable=True),
    sa.Column('posl_aktual', sa.TIMESTAMP(), server_default=sa.text('now()'), server_onupdate=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_zam'], ['zamestnanec.id_zam'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_skol')
    )
    op.create_table('denni_evidence',
    sa.Column('id_cinnosti', sa.Integer(), nullable=False),
    sa.Column('id_zam', sa.Integer(), nullable=False),
    sa.Column('den_uskut', sa.Date(), nullable=True),
    sa.Column('cas_uloz', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('cas_zmeny', sa.TIMESTAMP(), server_default=sa.text('now()'), server_onupdate=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_cinnosti'], ['cinnost.id_cinnosti'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_zam'], ['zamestnanec.id_zam'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_cinnosti', 'id_zam')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('denni_evidence')
    op.drop_table('skoleni_ridicu')
    op.drop_table('pracovni_sml')
    op.drop_table('lekarska_prohl')
    op.drop_table('dovolena_zam')
    op.drop_table('dokument')
    op.drop_table('cinnost')
    op.drop_table('zamestnanec')
    op.drop_table('vozidlo')
    op.drop_table('uzivatel')
    op.drop_table('typ_dokumentu')
    op.drop_table('sazba')
    # ### end Alembic commands ###
