"""Adding role column for the users

Revision ID: fe68d98489ec
Revises: 483b37ee1009
Create Date: 2018-10-30 18:07:16.368844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe68d98489ec'
down_revision = '483b37ee1009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uzivatel', sa.Column('role', sa.String(length=10), server_default='user', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uzivatel', 'role')
    # ### end Alembic commands ###
